### PR TITLE
Add date to listings

### PR DESCRIPTION
**Pull request by reynir**
Thanks for the feedback in #28 ! It was quite simple.

The output will look like

> Written by Foobar Baz (22.04.2016)

I put the timestamp in a <span> with the `date` class. I'm not sure if you agree with this. HTML and CSS is not my forte :-)

### CODE REVIEW

**Comment by dbuenzli** [comment]
> Written by Foobar Baz (22.04.2016)

I'd suggest using big-endian dates i.e. 2016-04-22, those are universally recognized as unambiguous which is not the case of little-endian ones where month and day numbers can misinterpreted depending on your locale.

> I put the timestamp in a with the date class. I'm not sure if you agree with this. HTML and CSS is not my forte :-)

I'd rather use a [time](https://www.w3.org/TR/html51/textlevel-semantics.html#the-time-element) element and no class.

**Comment by abbysmal** [comment]
@reynir: Thank you! :)

> I'd suggest using big-endian dates i.e. 2016-04-22, those are universally recognized as unambiguous which is not the case of little-endian ones where month and day numbers can misinterpreted depending on your locale.

I don't have anything to say against modifying how the date is displayed, big-endian dates looks indeed rather unambiguous. (changing them is as simple as editing the `ptime_to_pretty_date` function)

> I'd rather use a time element and no class.

Didn't knew about the time element, again I have nothing against using it, if you want to change it @reynir go ahead. :)

**Comment by reynir** [comment]
I changed the output into a <time> element. The timestamp is relatively big next to the author field. Maybe the CSS should be changed(?)

**Comment by abbysmal** [comment]
Will fix it after merging, everything looks good to me otherwise. So, merging. :)
Thank you!

**Comment by abbysmal** [comment]
And it's done, thank you again. :)

**Comment by reynir** [comment]
Great, thanks!

**Pull request merged**
