### PR TITLE
No assets

### PR DESCRIPTION
**Pull request by hannesm**
@Engil if you've some time to review... it works for me (but likely needs documentation for other people, that now the assets need to be in the git remote)

//cc @avsm since he has deployments as well

### CODE REVIEW

**Comment by hannesm** [comment]
this allowed me to use irmin 0.11.1 and git 1.8.0 on xen! :) live https://hannes.nqsb.io

**Comment by hannesm** [comment]
I made CI happy... another improvement of this is that we can now store pictures and pdf in the data repository, and link to them!

**Comment by hannesm** [comment]
I added a rudimentary (maybe working) `populate.sh` and put some blurb in the `README` about it..

**Comment by hannesm** [comment]
I rebased to current master and the shell script `populate.sh` is now run by the CI as well!

**Comment by hannesm** [comment]
now includes @voila changes which stores the major part of the configuration in the git remote! :)

**Comment by abbysmal** [comment]
Seems awesome!
Back from traveling, so I will have plenty of time in the next few days to review the PR, will do it today!
Does anybody got a test repository containing what's needed to run Canopy nowadays ? I can setup one myself but am rather lazy. 😶

**Comment by hannesm** [comment]
https://github.com/Engil/__blog/pull/1 (which just refers to https://github.com/hannesm/__blog.git should work) -- https://github.com/voila/blog-content.git as well

a preliminary `populate.sh` is available (but should likely be extended to generate a uuid in .config/uuid)  -- also see discussion in https://github.com/hannesm/Canopy/pull/2

**Comment by hannesm** [comment]
- I moved port and tls_port back as key arguments
- I put `.config/uuid` there, and read it from the store during startup.  once read, it must be present and will be used over the entire lifetime of the process/unikernel
- I also cleaned up some code, now works with `main.native -r git://github.com/hannesm/__blog.git` and `./main.native -r git://github.com/hannesm/hannes.nqsb.io.git#dev` (thx to @gasche)

//@voila @Engil @avsm I think this is ready for merge (now deploying)..

future: logging via syslog, would be nice (someone has time for that? @voila?): recent changes as atom feed :)

**Comment by hannesm** [comment]
closing in favour of #71

**Pull request closed without merging**
