### PR TITLE
Minor stylistic improvements

### PR DESCRIPTION
**Pull request by hannesm**
these are minor improvements (/cc @Engil @avsm) - I'm planning to merge them if CI passes

### CODE REVIEW

**Comment by abbysmal** [comment]
Thank you for this !
Not sure about the unused button but I think it's actually used, it should be the button that shows up when the browser resolution is small enough (it transform the links in the top bar into a togglable button to save space). (useful for mobile browsing)
Can't check at the moment, will do a bit later

**Comment by hannesm** [comment]
oh, wasn't aware of that, will revert that part here then..

**Comment by hannesm** [comment]
(force-pushed to retain the button)

**Comment by abbysmal** [comment]
There might be fancier and more explicit ways of handling that nowadays but that's as far as my frontend knowledge goes :)

**Comment by hannesm** [comment]
my edits are from a branch where I removed bootstrap.css (and thus had no fancy magic for the button), and I wasn't aware that the button actually had a purpose ;)

**Comment by hannesm** [comment]
@Engil travis is happy again, please merge if you're fine with the changes :D

**Comment by abbysmal** [comment]
LGTM, merged !
Thank you!

**Pull request merged**
