### PR TITLE
Port to Irmin 1.0 and Mirage 3.0

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
All green!

**Comment by samoht** [comment]
@hannesm yiikes. You might maybe want to revert 0c0f001 when https://github.com/ocaml/opam-repository/pull/8535 is merged

**Comment by hannesm** [comment]
@samoht yes, that's the plan

**Comment by hannesm** [comment]
(but I couldn't await to merge the Mirage3 PR ;)

**Pull request merged**
