### PR TITLE
MirageOS3 port

### PR DESCRIPTION
**Pull request by hannesm**
this compiles at least locally (no clue how to let CI use the mirage-dev remote)

### CODE REVIEW

**Comment by abbysmal** [comment]
Hello,
Thank you, looks great !
I think the CI just needs some addition to the Dockerfile, I added
```
RUN opam repo add mirage-dev https://github.com/mirage/mirage-dev.git
RUN opam update -yu
```
Just before the `opam install mirage` line and it looks like it worked, except the compilation somehow fails this way on my machine (running Docker)

```
opam@2f803163b903:/src$ opam config exec -- mirage build

run ['ocaml-crunch' '-o' 'static1.ml' 'tls']: exited with 127opam@2f803163b903:/src$ cat static1.ml
cat: static1.ml: No such file or directory
opam@2f803163b903:/src$
```
I will take a deeper look without Docker tomorrow

**Comment by hannesm** [comment]
you'll need to adapt to the new workflow: `mirage configure <options>` followed by `make depend` and `mirage build`.  I suspect the `make depend` is missing (dependency installation was previously (in Mirage2) done during the `configure` (or `build`) step, but this is no longer the case (instead, it has to be done explicitly).

**Comment by abbysmal** [comment]
`make depend` was missing indeed, now having some troubles with
```
# File "src-mirage/irmin_mirage.mli", line 64, characters 45-54:
# Error: Unbound module V1
```
But I will figure this out tomorrow, probably some package to pin

**Comment by abbysmal** [comment]
Or we can as well just wait for the Mirage3 release to fix CI 😇

**Comment by hannesm** [comment]
see https://github.com/mirage/irmin/pull/396 (or pin irmin-mirage to https://github.com/hannesm/irmin.git#mirage3-fixes)

**Comment by hannesm** [comment]
(now merged, no further pin apart from mirage-dev remote repo should be needed)

**Comment by amirmc** [comment]
@hannesm Does this work with `mirageos-3-beta` remote? More specifically, can we switch over to the upstreamed packages after they're released and rebuild/redeploy canopy.mirage.io?

I'm just trying to get an idea of where things stand.

**Comment by hannesm** [comment]
mostly -- need some minor things due to @samoht irmin 1.0 release (I guess)...  I'll take care of this being ready (and merged into master before the release) :)

rebuilding/redeploying canopy.mirage.io:  no clue, I don't run it (and don't have access to it -- I also don't want to have access to it)

**Comment by hannesm** [comment]
to do so, a tyxml release is required (@Drup -- any chance to get a tyxml release soon?): irmin-1.0.0 depends on uutf-1.0.0, which conflicts with tyxml-4.0.1

**Comment by Drup** [comment]
Oups. Yell at me next wednesday if I haven't done it yet.

**Comment by hannesm** [comment]
and for the irmin-related changes: I can't figure out atm how irmin_mirage API changed (in canopy_store, maybe @samoht has some advice what to do there). :)

**Comment by samoht** [comment]
See #79

**Comment by hannesm** [comment]
included in #79

**Pull request closed without merging**
