### PR TITLE
issue #2: Mime type handling

### PR DESCRIPTION
**Pull request by voila**
Following @samoht suggestion #2 , use magic-mime to add a Content-Type header for static files.

### CODE REVIEW

**Comment by abbysmal** [comment]
Great!
Looks like it's alright, I will test it later today then merge.
Only thing I see right now if that you need to add the dependency to magic-mime inside Canopy's config.ml.
Looks great otherwise, thank you. :)

**Comment by hannesm** [comment]
(this conflicts slightly with #15) - not a big deal, but either will need a rebase and manual fix...

**Comment by voila** [comment]
Sorry about missing the package... it was already installed on my system and I assumed it was already in the config...

**Comment by hannesm** [comment]
(now that #15 is merged, this needs to live in `canopy_dispatch`... sorry)

**Pull request closed without merging**
