### PR TITLE
Update to dev version of ocaml-git + ngit branch of irmin

### PR DESCRIPTION
**Pull request by samoht**
To be compiled with the following instructions:

```
$ opam pin add git -n --dev
$ opam pin add git-http -n --dev
$ opam pin add git-mirage -n --dev
$ opam pin add irmin --dev
$ opam pin add irmin-git --dev
$ opam pin add irmin-mem --dev
$ opam pin add irmin-mirage --dev
```

### CODE REVIEW

**Comment by hannesm** [comment]
I tried with these instruction (NB: unix backend using sockets, since bigstringaf does not work on freestanding yet - debugged and reported thanks to samoht elsewhere):

1. using `-r git://github.com/Engil/__blog.git`
console output:
```
2018-05-19 13:06:55 +02:00: INF [canopy-store] pulling repository
2018-05-19 13:06:55 +02:00: DBG [irmin.sync] fetch URI git://github.com/Engil/__blog.git
2018-05-19 13:06:55 +02:00: DBG [irmin.sync] Fetching branch master
2018-05-19 13:06:55 +02:00: DBG [irmin.git] fetch git://github.com/Engil/__blog.git
2018-05-19 13:06:55 +02:00: DBG [git.mem] Ref.list
2018-05-19 13:06:55 +02:00: DBG [negociator] Local references: .
2018-05-19 13:06:55 +02:00: DBG [git.sync] fetch_ext git://github.com/Engil/__blog.git
2018-05-19 13:06:55 +02:00: DBG [git.sync] Start to process the flow.
```
gdb backtrace:
```
(gdb) bt
#0  _select () at _select.S:3
#1  0x0000000800d871c2 in __thr_select (numfds=8, readfds=0x7fffffffe1c0, writefds=0x7fffffffe240, exceptfds=0x7fffffffe2c0, timeout=0x0)
    at /usr/home/hannes/devel/freebsd/lib/libthr/thread/thr_syscalls.c:495
#2  0x0000000000a1f4cb in unix_select ()
#3  0x000000000087fb73 in camlLwt_engine__fun_3096 () at src/unix/lwt_engine.ml:419
#4  0x000000000087f756 in camlLwt_engine__fun_3023 () at src/unix/lwt_engine.ml:360
#5  0x0000000000881e3c in camlLwt_main__run_1127 () at src/unix/lwt_main.ml:49
#6  0x0000000000615b67 in camlMain__entry () at main.ml:158
#7  0x000000000060ef39 in caml_startup.code_begin ()
#8  0x0000000000a425de in caml_start_program ()
#9  0x0000000000a42928 in caml_startup_common (argv=0x7fffffffe5c0, pooling=<optimized out>) at startup.c:156
#10 0x0000000000a4298b in caml_startup_exn (argv=0x8) at startup.c:161
#11 caml_startup (argv=0x8) at startup.c:166
#12 caml_main (argv=0x8) at startup.c:173
#13 0x0000000000a22c5c in main (argc=<optimized out>, argv=0x8) at main.c:44
(gdb) thread 2
[Switching to thread 2 (LWP 100224 of process 63703)]
#0  _umtx_op_err () at /usr/home/hannes/devel/freebsd/lib/libthr/arch/amd64/amd64/_umtx_op_err.S:37
37      RSYSCALL_ERR(_umtx_op)
(gdb) bt
#0  _umtx_op_err () at /usr/home/hannes/devel/freebsd/lib/libthr/arch/amd64/amd64/_umtx_op_err.S:37
#1  0x0000000800d863d1 in _thr_umtx_timedwait_uint (mtx=0x8024eb008, id=<optimized out>, clockid=<optimized out>, abstime=<optimized out>, 
    shared=<optimized out>) at /usr/home/hannes/devel/freebsd/lib/libthr/thread/thr_umtx.c:236
#2  0x0000000800d8ff58 in cond_wait_user (abstime=0x0, cancel=1, cvp=<optimized out>, mp=<optimized out>)
    at /usr/home/hannes/devel/freebsd/lib/libthr/thread/thr_cond.c:306
#3  cond_wait_common (cond=<optimized out>, mutex=<optimized out>, abstime=0x0, cancel=1) at /usr/home/hannes/devel/freebsd/lib/libthr/thread/thr_cond.c:366
#4  0x00000000009f9902 in lwt_unix_condition_wait (condition=0x108fd30 <pool_condition>, mutex=0x108fd28 <pool_mutex>) at lwt_unix_stubs.c:241
#5  worker_loop (data=0x8024ce000) at lwt_unix_stubs.c:1145
#6  0x0000000800d84425 in thread_start (curthread=0x800d71500) at /usr/home/hannes/devel/freebsd/lib/libthr/thread/thr_create.c:291
#7  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdfffe000
```
network: 
after DNS resolution of github.com, a TCP session is established (three way handshake), but the client (Canopy) never sends any data to the server.

2. using `-r http://github.com/Engil/__blog.git`
console output is the same
gdb:
```
(gdb) bt
#0  _read () at _read.S:3
#1  0x0000000800d87016 in __thr_read (fd=7, buf=0x80299e000, nbytes=4096) at /usr/home/hannes/devel/freebsd/lib/libthr/thread/thr_syscalls.c:420
#2  0x00000000009fa26c in lwt_unix_bytes_read (val_fd=<optimized out>, val_buf=<optimized out>, val_ofs=<optimized out>, val_len=<optimized out>)
    at unix_bytes_read.c:36
#3  0x000000000088b343 in camlLwt_bytes__fun_2327 () at src/unix/lwt_bytes.ml:133
#4  0x0000000000884479 in camlLwt_unix__fun_4516 () at src/unix/lwt_unix.cppo.ml:563
#5  0x000000000086fd1d in camlTcp_socket__fun_2492 () at lwt/lwt_cstruct.ml:18
#6  0x0000000000899eac in camlLwt__catch_24942 () at src/core/lwt.ml:2046
#7  0x00000000008916d1 in camlMirage_flow__read_1424 () at src/mirage_flow.ml:79
#8  0x00000000007f1025 in camlMirage_channel_lwt__ibuf_refill_1504 () at lwt/mirage_channel_lwt.ml:68
#9  0x00000000007f13a6 in camlMirage_channel_lwt__get_ibuf_1783 () at lwt/mirage_channel_lwt.ml:88
#10 0x00000000007f1560 in camlMirage_channel_lwt__read_some_1793 () at lwt/mirage_channel_lwt.ml:105
#11 0x00000000006773ac in camlGit_mirage__Net__read_1913 () at src/git-mirage/net.ml:43
#12 0x00000000006cbea3 in camlGit__Sync__process_125278 () at src/git/sync.ml:472
#13 0x000000000089906e in camlLwt__callback_13871 () at src/core/lwt.ml:1887
#14 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#15 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#16 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#17 0x000000000089908f in camlLwt__callback_13871 () at src/core/lwt.ml:1901
#18 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#19 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#20 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#21 0x000000000089908f in camlLwt__callback_13871 () at src/core/lwt.ml:1901
```
CPU usage is at 100%!
network the same (DNS resolution, TCP three-way handshake)
3. using `-r https://github.com/Engil/__blog.git`:
console output as above
gdb
```
#0  camlGit__Sync__fun_196760 () at src/git/sync.ml:474
#1  0x000000000089906e in camlLwt__callback_13871 () at src/core/lwt.ml:1887
#2  0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#3  0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#4  0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#5  0x000000000089908f in camlLwt__callback_13871 () at src/core/lwt.ml:1901
#6  0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#7  0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#8  0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#9  0x000000000089908f in camlLwt__callback_13871 () at src/core/lwt.ml:1901
#10 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#11 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#12 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#13 0x000000000089908f in camlLwt__callback_13871 () at src/core/lwt.ml:1901
#14 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#15 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#16 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#17 0x0000000000899b7b in camlLwt__callback_21926 () at src/core/lwt.ml:2010
#18 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#19 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#20 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#21 0x0000000000899b7b in camlLwt__callback_21926 () at src/core/lwt.ml:2010
#22 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#23 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#24 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#25 0x000000000089908f in camlLwt__callback_13871 () at src/core/lwt.ml:1901
#26 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#27 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#28 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#29 0x000000000089908f in camlLwt__callback_13871 () at src/core/lwt.ml:1901
#30 0x0000000000897b68 in camlLwt__iter_callback_list_4529 () at src/core/lwt.ml:1230
#31 0x0000000000897cd9 in camlLwt__run_in_resolution_loop_4573 () at src/core/lwt.ml:1296
#32 0x0000000000897e87 in camlLwt__resolve_4591 () at src/core/lwt.ml:1332
#33 0x00000000008980dc in camlLwt__wakeup_general_4627 () at src/core/lwt.ml:1406
#34 0x00000000009aeebc in camlArray__iter_1057 () at array.ml:90
#35 0x00000000008964ad in camlLwt_sequence__loop_1061 () at src/core/lwt_sequence.ml:144
#36 0x00000000009a7731 in camlList__iter_1083 () at list.ml:100
```
network: DNS resolution, TCP connection, TLS establishment.

I suspect somewhere in irmin/git (or in this PR) we need to send some data to the server before reading the stream.  I also don't understand why (2, http) leads to a busy loop.

**Comment by dinosaure** [comment]
Follow [dinosaure/Canopy#irmin2](https://github.com/dinosaure/Canopy/tree/irmin2) now. I can not push on @samoht's branch ... It's work with a pin of all `irmin-*` packages (including `irmin-mirage-git` which is new). Need to have a `_tags` file with:

```
true: package(digestif.c checkseum.c)
```

Then, the linker for `hvt` will fail (due to _variantization_ of `digestif` and `checkseum`), so you need to trick on the linker with:

```ld
  '-L$HOME/.opam/4.07.1/lib/digestif'
  '-l:rakia/freestanding/librakia_freestanding_stubs.a'
  '-L$HOME/.opam/4.07.1/lib/checkseum'
  '-l:laolao/freestanding/liblaolao_freestanding_stubs.a'
```

Then, to get `solo5-hvt`, you need to compile it with `mirage-skeleton` repository. Go into `device-usage/network`, launch a `mirage configure -t hvt` & `mirage build` and copy the `solo5-hvt` into the Canopy repository. Finally:

```sh
$ ./solo5-hvt --net=tap100 -- canopy.hvt
```

**Comment by mato** [comment]
@dinosaure:

Trying to get your `irmin2` branch working. I can pin `irmin` to `--dev-repo`, but pinning `irmin-git` causes OPAM to remove `mirage-runtime`:

```
[irmin-git.1.3.0] synchronised from git+https://github.com/mirage/irmin.git
irmin-git is now pinned to git+https://github.com/mirage/irmin.git (version dev)

The following actions will be performed:
  ∗ install   psq            0.2.0  [required by lru]
  ⊘ remove    mirage         3.6.0  [uses mirage-runtime]
  ∗ install   ke             0.4    [required by git]
  ∗ install   bigstringaf    0.6.0  [required by angstrom]
  ∗ install   cstruct        5.0.0  [required by git]
  ∗ install   optint         0.0.3  [required by checkseum, decompress]
  ∗ install   lru            0.3.0  [required by git]
  ⊘ remove    mirage-runtime 3.6.0  [conflicts with checkseum]
  ∗ install   angstrom       0.12.1 [required by git]
  ∗ install   hex            1.4.0  [required by git]
  ∗ install   duff           0.2    [required by git]
  ↻ recompile eqaf           0.5    [uses cstruct]
  ∗ install   checkseum      0.1.1  [required by git]
  ∗ install   encore         0.3    [required by git]
  ↻ recompile digestif       0.7.4  [uses eqaf]
  ∗ install   decompress     0.9.1  [required by git]
  ↻ recompile irmin          dev*   [uses digestif]
  ∗ install   git            2.1.1  [required by irmin-git]
  ∗ install   irmin-git      dev*
===== ∗ 14   ↻ 3   ⊘ 2 =====
```

What can be done to fix this?

**Comment by hannesm** [comment]
not being @dinosaure, but this fix https://github.com/mirage/ocaml-git/commit/62d581cb5fbe4109cbb19924d37aa808c2ab883a should to be added to the opam-repository released `git` package(s) -- or `git` being pinned to `--dev-repo`

**Comment by mato** [comment]
Ok, the following minimal list of pins works:

```
git.2.1.1               git  git+https://github.com/mirage/ocaml-git.git
irmin.dev               git  git+https://github.com/mirage/irmin.git
irmin-git.dev           git  git+https://github.com/mirage/irmin.git
irmin-mem.dev           git  git+https://github.com/mirage/irmin.git
irmin-mirage.dev        git  git+https://github.com/mirage/irmin.git
irmin-mirage-git.dev    git  git+https://github.com/mirage/irmin.git
```

To actually get the (hvt) unikernel to build:

1.  the `.ocaml` variant for `checkseum` needs to be added to `requires` in `$(opam config var prefix)/lib/decompress/META`
2. the `.ocaml` variant for `digestif` needs to be added to `requires` in vi `$(opam config var prefix)/lib/git/META`

**Comment by mato** [comment]
Ok, running (with outgoing NAT enabled on tap100):

    solo5-hvt --net:service=tap100 -- ./canopy.hvt --remote=https://github.com/mirage/mirage-canopy.git

I get:

```
2019-10-17 12:13:17 -00:00: INF [canopy-store] pulling repository
2019-10-17 12:13:18 -00:00: ERR [git.sync.http] The HTTP decoder returns an error: (`No_assert_predicate #predicate).
2019-10-17 12:13:18 -00:00: WRN [canopy-store] failed pull (Invalid_argument "Sync.pull_exn: (`Sync Repository not found.)")
2019-10-17 12:13:18 -00:00: ERR [application] main: (Invalid_argument ".config/uuid is required in the remote git repository")
Raised at file "stdlib.ml", line 30, characters 20-45
Called from file "src/core/lwt.ml", line 2011, characters 35-40
Re-raised at file "src/core/lwt.ml", line 2999, characters 20-29
Called from file "lib/main.ml", line 72, characters 15-25

Solo5: solo5_exit(1) called
```

Full debug log attached. Any ideas?
[log.txt](https://github.com/Engil/Canopy/files/3739174/log.txt)

**Comment by hannesm** [comment]
@mato could you try with `--remote=https://github.com/mirage/canopy-data.git` (canopy-data instead of mirage-canopy)?

**Comment by mato** [comment]
@hannesm Ah indeed, that works, silly typo on my part. Then again, the error message was not obvious (expected "Not a git repository at URL", as opposed to ".config/uuid is required in the remote git repository")

Thanks.

**Comment by hannesm** [comment]
reading your output:

```
2019-10-17 12:13:17 -00:00: INF [canopy-store] pulling repository
2019-10-17 12:13:18 -00:00: ERR [git.sync.http] The HTTP decoder returns an error: (`No_assert_predicate #predicate).
2019-10-17 12:13:18 -00:00: WRN [canopy-store] failed pull (Invalid_argument "Sync.pull_exn: (`Sync Repository not found.)")
```

i feel the last line should be fatal and exit, not report a warning and attempt to continue -- it seems to be reported by canopy, so the error handling in canopy_store.ml should be adjusted :)

**Comment by dinosaure** [comment]
> 1. the .ocaml variant for checkseum needs to be added to requires in $(opam config var prefix)/lib/decompress/META
> 2. the .ocaml variant for digestif needs to be added to requires in vi $(opam config var prefix)/lib/git/META

Just to let a trick, into your unikernel workspace, if you add a `_tags` file with:
```
true: package(checkseum.ocaml digestif.ocaml)
```

It should work. Then, if you keep `digestif.0.7.4` and `checkseum.0.0.9`, you should be able to use `digestif.c` and `checkseum.c`.

**Comment by hannesm** [comment]
I pushed some commits fixing the CI system (the used docker image was no longer available and a bit old, ocaml 4.03), and with the actual irmin2 releases (including @dinosaure suggestion to have a `_tags` file to select `digestif.c` and `checkseum.c`). Now the CI is green and I'm merging this branch since it improves the user experience tremendously.

**Comment by mato** [comment]
@hannesm Thanks for this! I can confirm the `master` branch now works with Irmin2, no OPAM pins required. I've also updated http://canopy.mirage.io/ to `master` from this repository.

**Pull request merged**
